version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - mongodb_data:/data/db

  mongoku:
    image: huggingface/mongoku:latest
    container_name: mongoku
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8082:3100"
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb://mongodb:$DB_PORT"

volumes:
  mongodb_data:
 